### ISSUE TITLE
Move website files out of this repo

### ISSUE THREAD

**Issue by jeffbaumes** [kitware-data-solutions/miqa-phase1#120]
Keeping with the transition away from this repo, I recommend moving the website code to its own repo, miqa-website, in this org. It should contain the contents of the [docs folder of the miqa-website branch](https://github.com/OpenImaging/miqa/tree/miqa-website/docs) on this repo. Preserving git history is not necessary.

After the site files are there, it will require an update to netlify configuration, which will probably just take a few minutes of @brianhelba 's time.

When this is done we can start putting specific issues on that repo for changes.

**Comment by brianhelba** [comment]
Sounds good, let me know.

**Comment by jeffbaumes** [comment]
Ok @brianhelba you're up. The new code for Netlify to watch is the `main` branch of `OpenImaging/miqa-landing-page`. Let me know what access you need to change this.

**Comment by brianhelba** [comment]
@jeffbaumes I need admin access to that repo, https://github.com/OpenImaging/miqa-landing-page for now. I intend to remove myself when the setup is complete.

**Comment by jeffbaumes** [comment]
Ok @brianhelba admin access given, let me know if you need anything else.

**Comment by brianhelba** [comment]
@jeffbaumes The build is set up. To ensure that branch previews are triggered correctly, I need to install the Netlify "app" to GitHub.

Accordingly, can you invite me as a team member to the `OpenImaging` organization: https://github.com/orgs/OpenImaging/people
Right now, I assume I'm an outside collaborator.

**Comment by brianhelba** [comment]
This is fully resolved, and the build is now working: https://miqa.kitware.com/
