### ISSUE TITLE
Client build broken

### ISSUE THREAD

**Issue by scottwittenburg** [kitware-data-solutions/miqa-phase1#14]
Following the developer setup instructions, the step building the client application (`npm run serve`) fails with a bunch of errors like the following:

```
 error  in ./src/App.vue?vue&type=style&index=0&lang=scss&

Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
Require stack:
- /Users/scott/projects/miqa/miqa/client/node_modules/sass-loader/lib/loader.js
- /Users/scott/projects/miqa/miqa/client/node_modules/loader-runner/lib/loadLoader.js
- /Users/scott/projects/miqa/miqa/client/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/scott/projects/miqa/miqa/client/node_modules/webpack/lib/NormalModule.js
- /Users/scott/projects/miqa/miqa/client/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/scott/projects/miqa/miqa/client/node_modules/webpack/lib/Compiler.js
- /Users/scott/projects/miqa/miqa/client/node_modules/webpack/lib/webpack.js
- /Users/scott/projects/miqa/miqa/client/vue.config.js
- /Users/scott/projects/miqa/miqa/client/node_modules/@vue/cli-service/lib/Service.js
- /Users/scott/projects/miqa/miqa/client/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.sassLoader (/Users/scott/projects/miqa/miqa/client/node_modules/sass-loader/lib/loader.js:46:72)

 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/lib/loader.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=scss& 4:14-415 14:3-18:5 15:22-423
 @ ./src/App.vue?vue&type=style&index=0&lang=scss&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

Complete error log attached.

[client-build-error.txt](https://github.com/OpenImaging/miqa/files/4997296/client-build-error.txt)

**Comment by scottwittenburg** [comment]
@aashish24 @thewtex Seems I need more permission in order to be able to assign issues to myself on this repository.  Can one of you make me part of "write access", "admin access", or "owners" team on this organization?  According to this [SO](https://stackoverflow.com/questions/26752902/how-to-assign-issue-to-myself-at-github), that would do the trick.

**Comment by thewtex** [comment]
@scottwittenburg according to the Collaborators section, you have Admin access, but have not yet accepted the invitation to the repository (there should be an email in your inbox).

**Comment by scottwittenburg** [comment]
> @scottwittenburg according to the Collaborators section, you have Admin access, but have not yet accepted the invitation to the repository (there should be an email in your inbox).

Whoops, you're right, there was an invitation in my inbox.  When I received it, I just followed the link to the repo instead of viewing the invitation.  Now, unfortunately, it has expired, sorry.  Can it be resent or refreshed or something?

**Comment by thewtex** [comment]
@scottwittenburg :+1: resent

**Comment by scottwittenburg** [comment]
> @scottwittenburg 👍 resent

Thanks I accepted it this time.
