### ISSUE TITLE
Cache more images in memory

### ISSUE THREAD

**Issue by scottwittenburg** [kitware-data-solutions/miqa-phase1#31]
Currently the application fetches and caches only the timesteps for the current scan.  We should increase to caching the entire current session.  It would also be nice to show some indication in the UI of which scans are currently in memory.  

We can evaluate how this works in practice (does it put too much memory pressure on the application), and perhaps eventually allow the user more control of which images are loaded.

**Comment by aashish24** [comment]
@scottwittenburg is this still relevant?

**Comment by scottwittenburg** [comment]
It was merged with #35

**Comment by aashish24** [comment]
thanks. So does it make sense to close it?
