### ISSUE TITLE
Image for Wiki page

### ISSUE THREAD

**Issue by matthewma7** [kitware-data-solutions/miqa-phase1#5]
![chrome_2019-08-22_10-04-30](https://user-images.githubusercontent.com/3123478/63540571-4a553400-c4ea-11e9-9538-69f82b82f65b.png)
![chrome_2019-08-31_19-08-43](https://user-images.githubusercontent.com/3123478/64069939-3e245180-cc23-11e9-8ba4-aae219f302c4.png)
![chrome_2019-08-06_14-35-18](https://user-images.githubusercontent.com/3123478/62567256-d1eb4380-b858-11e9-98cc-0bced2aa0c0c.png)

**Comment by aashish24** [comment]
@matthewma7 can we close this?

**Comment by matthewma7** [comment]
![output](https://user-images.githubusercontent.com/3123478/63644049-df545a80-c6ad-11e9-8a32-22b18c3add25.gif)
