### ISSUE TITLE
Create better data statistics for PredictHD

### ISSUE THREAD

**Issue by dzenanz** [kitware-data-solutions/miqa-phase1#61]
Hans said there is a minor update to data, so I should probably wait for that.

**Comment by jeffbaumes** [comment]
CSV file about quality control information has 10422 entries. Among transferred files, Existing image: 9475, non-existent files: 947. @dzenanz will look into Globus transfer or get back to Hans on how to get missing files.

**Comment by dzenanz** [comment]
The images are missing in the original set shared by Hans. Waiting on @hjmjohnson's reply.
