### ISSUE TITLE
Create MIQA static website 

### ISSUE THREAD

**Issue by aashish24** [kitware-data-solutions/miqa-phase1#77]

**Comment by aashish24** [comment]
Example website that we are trying to copy: https://kitware.github.io/resonanthpc/

**Comment by aashish24** [comment]
@jeffbaumes here is the rough draft / outline I created earlier https://docs.google.com/document/d/1eAPtYuLMVtnAP9wycJfGEp0m2fSXlGyky3Lix1Fgd_I/edit#

**Comment by jeffbaumes** [comment]
Thanks, I requested access since I don't have permissions on it yet.

**Comment by jeffbaumes** [comment]
Faiza created this mockup:

https://www.figma.com/file/oQBnEsHl2frHpcqQhwfQgs/Site?node-id=0%3A1

It is ready for implementation, Jared will be setting up a framework for this in the next few days.

There are places where we need more text for features, I've asked @curtislisle can take a pass at that.

**Comment by jeffbaumes** [comment]
This is currently planned to be hosted at https://miqa.kitware.com

**Comment by curtislisle** [comment]
I wasn't able to edit, so I copied to my own draft and edited the text.  I sent invitations for review of the text.   My edits can be viewed here: https://www.figma.com/file/oQBnEsHl2frHpcqQhwfQgs/Site?node-id=2%3A15

**Comment by faiza-a** [comment]
@curtislisle The Mockups i share don't have editing rights to anyone to keep the mockups from accidental edits :)
When you want to suggest text or changes. you can add comments on the mockups. use the 💬 button and drop comment anywhere on mockup.
Also the above link you share points to the mockup i shared. could you check your Figma link again

**Comment by curtislisle** [comment]
@faiza-a  Sorry I posted the wrong link.  Please try this one.  https://www.figma.com/file/P7Pbmb3kqYc32HXRJqBchE/Site-Copy?node-id=2%3A15.  Now I know to use the comment button from now on.  Thanks for explaining the process to me. :-) 

I edited the bullets (the lorem ipsum... passages) as well as tweaking the wording in the major headings.  Thanks.

**Comment by faiza-a** [comment]
@curtislisle Thanks for your help on this. I have updated the original [mockup file ](https://www.figma.com/file/oQBnEsHl2frHpcqQhwfQgs/Site?node-id=0%3A1) with your changes. Please let me know if i missed anything.
Feel free to suggest any other changes too if needed. 
We will be working on building the site shortly.

**Comment by jeffbaumes** [comment]
I'm going to close this one since miqa.kitware.com is now live, but will open new issues for further changes.
