### ISSUE TITLE
Add a client status of time till session expiry

### ISSUE THREAD

**Issue by jeffbaumes** [kitware-data-solutions/miqa-phase1#92]
4/14 discussion that UI will show a "time remaining" when the timeout time is approaching.  System will not auto-renew timeout for initial version, but this is enough to warn the user for the first version.

**Comment by jeffbaumes** [comment]
This could be a warning banner with an updating remaining time after sub-5-minutes. There could be a "logout now to refresh session" convenience button that performs a logout.

**Comment by scottwittenburg** [comment]
#91 addresses this in a basic way
